apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app.kubernetes.io/component: client
spec:
  selector:
    app.kubernetes.io/component: client
  ports:
    - port: 80
  sessionAffinity: ClientIP
