apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: client

  template:
    metadata:
      labels:
        app.kubernetes.io/component: client
    spec:
      containers:
        - name: client
          image: ghcr.io/digitalinteraction/pdc-client
          resources:
            requests: { memory: 32Mi, cpu: 50m }
            limits: { memory: 128Mi, cpu: 100m }
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/config.js
              name: resources
              subPath: config.js
            - mountPath: /etc/nginx/conf.d/default.conf
              name: resources
              subPath: nginx.conf
            - mountPath: /usr/share/nginx/html/static
              name: static
          readinessProbe:
            tcpSocket: { port: 80 }
            initialDelaySeconds: 1
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5

      volumes:
        - name: resources
          configMap:
            name: client-resources
        - name: static
          persistentVolumeClaim:
            claimName: static
