apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: server

  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/digitalinteraction/pdc-server
          envFrom:
            - secretRef: { name: server-env }
          args:
            - migrate

      containers:
        - name: server
          image: ghcr.io/digitalinteraction/pdc-server
          resources:
            requests: { memory: 64Mi, cpu: 500m }
            limits: { memory: 256Mi, cpu: 600m }
          ports:
            - name: web
              containerPort: 3000
          envFrom:
            - secretRef: { name: server-env }
          readinessProbe:
            tcpSocket: { port: 3000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 5
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /app/app-config.json
              name: resources
              subPath: app-config.json
              readOnly: true

      # Volumes
      volumes:
        - name: resources
          configMap:
            name: server-resources

      # Security
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
