apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/component: server
  ports:
    - port: 3000
  sessionAffinity: ClientIP
