apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: setup
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/digitalinteraction/pdc-server
          args:
            - migrate
          volumeMounts:
            - mountPath: /app/app-config.json
              name: resources
              subPath: app-config.json
              readOnly: true
            - mountPath: /app/do-ca.crt
              name: digitalocean
              subPath: do-ca.crt

        - name: settings
          image: ghcr.io/digitalinteraction/pdc-server
          args:
            - fetch-schedule
            - --only=settings
          volumeMounts:
            - mountPath: /app/app-config.json
              name: resources
              subPath: app-config.json
              readOnly: true
            - mountPath: /app/do-ca.crt
              name: digitalocean
              subPath: do-ca.crt

      volumes:
        - name: resources
          configMap:
            name: server-resources
        - name: digitalocean
          configMap:
            name: digitalocean

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
