apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-visitors
  labels:
    app.kubernetes.io/component: log-visitors
spec:
  # Runs every hour
  schedule: '0 * * * *'
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 200

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: log-visitors
        spec:
          restartPolicy: OnFailure
          containers:
            - name: log-visitors
              image: ghcr.io/digitalinteraction/pdc-server
              volumeMounts:
                - mountPath: /app/app-config.json
                  name: resources
                  subPath: app-config.json
                  readOnly: true
                - mountPath: /app/do-ca.crt
                  name: digitalocean
                  subPath: do-ca.crt
              env:
                - name: DEBUG
                  value: deconf*,pdc*
              resources:
                requests: { memory: 64Mi, cpu: 200m }
                limits: { memory: 128Mi, cpu: 300m }
              args:
                - log-visitors

          volumes:
            - name: resources
              configMap:
                name: server-resources
            - name: digitalocean
              configMap:
                name: digitalocean

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
