apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: server-env
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: server-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pdc/dev/server
