apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alerts-sendgrid
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: alerts-sendgrid
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pdc/alerts-sendgrid
