apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
        - name: server
          envFrom:
            - secretRef: { name: prod-server-env }
