apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
        - name: server
          envFrom:
            - secretRef: { name: dev-server-env }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      initContainers:
        - name: migrate
          envFrom:
            - secretRef: { name: dev-server-env }
