apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job
spec:
  template:
    spec:
      containers:
        - name: migrate
          envFrom:
            - secretRef: { name: dev-server-env }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job
spec:
  template:
    spec:
      containers:
        - name: settings
          envFrom:
            - secretRef: { name: dev-server-env }
