apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-schedule
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetch-schedule
              envFrom:
                - secretRef: { name: prod-server-env }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-schedule
spec:
  # Runs every day
  schedule: '0 6 * * *'
