apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-visitors
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: log-visitors
              envFrom:
                - secretRef: { name: prod-server-env }
